name: Build resume

on:
  push:
    branches:
      - main
    paths:
      - "**.tex"

jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: Update PDF
        uses: EndBug/add-and-commit@v9
        with:
          add: "resume.pdf"
          message: "Update pdf according to latex changes"
          committer_name: GitHub Actions
          committer_email: actions@github.com
